export const keys = {
  TAB: "TAB",
  DRAFT_LIST: "DRAFT_LIST",
  PLAYER_A_DRAFT_ORDER: "PLAYER_A_DRAFT_ORDER",
  PLAYER_B_DRAFT_ORDER: "PLAYER_B_DRAFT_ORDER",
  EXCLUSION_DRAFT_LIST: "EXCLUSION_DRAFT_LIST",
};
